DROP DATABASE soccer_league;
CREATE DATABASE soccer_league;
\c soccer_league;

CREATE TABLE teams (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
location TEXT NOT NULL);

CREATE TABLE players (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
birthdate DATE NOT NULL,
team_id INTEGER REFERENCES teams ON DELETE SET NULL);

CREATE TABLE seasons (
id SERIAL PRIMARY KEY,
start_date DATE NOT NULL,
end_date DATE NOT NULL);

CREATE TABLE matches (
id SERIAL PRIMARY KEY,
date DATE NOT NULL,
location TEXT NOT NULL,
team1_id INTEGER REFERENCES teams ON DELETE SET NULL,
team2_id INTEGER REFERENCES teams ON DELETE SET NULL,
season_id INTEGER REFERENCES seasons ON DELETE SET NULL);

CREATE TABLE goals (
id SERIAL PRIMARY KEY,
match_id INTEGER REFERENCES matches ON DELETE CASCADE,
player_id REFERENCES players ON DELETE SET NULL);

CREATE TABLE referees (
id SERIAL INTEGER PRIMARY KEY,
name TEXT NOT NULL);

CREATE TABLE ref_match (
id SERIAL PRIMARY KEY,
ref_id INTEGER REFERENCES referees ON DELETE CASCADE,
match_id INTEGER REFERENCES matches ON DELETE CASCADE);

CREATE TABLE results (
id SERIAL PRIMARY KEY,
team_id INTEGER REFERENCES teams ON DELETE CASCADE,
match_id INTEGER REFERENCES matches ON DELETE CASCADE,
result INTEGER NOT NULL)
-- 0 for loss, 1 for draw, 2 for win