DROP DATABASE craigslist_db;
CREATE DATABASE craigslist_db;
\c craigslist_db;

CREATE TABLE regions (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL);

CREATE TABLE users(
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
username VARCHAR(15) NOT NULL,
password VARCHAR(20) NOT NULL,
email VARCHAR(30) NOT NULL,
pref_region_id INTEGER REFERENCES regions ON DELETE SET NULL);

CREATE TABLE posts(
id SERIAL PRIMARY KEY,
title VARCHAR(25) NOT NULL,
text TEXT NOT NULL,
user_id INTEGER REFERENCES users ON DELETE CASCADE,
region_id INTEGER REFERENCES regions ON DELETE SET NULL);

CREATE TABLE categories (
id SERIAL PRIMARY KEY,
name VARCHAR(20) NOT NULL,
description TEXT);

CREATE TABLE post_category (
id SERIAL PRIMARY KEY,
post_id INTEGER REFERENCES posts ON DELETE CASCADE,
category_id INTEGER REFERENCES categories ON DELETE SET NULL);
